version: '3.4'

services:
  bcc.auth.server:
    image: ${DOCKER_REGISTRY-}bccauthserver
    build:
      context: .
      dockerfile: Bcc.Auth.Server/Dockerfile
  ravendb:
        image: ravendb/ravendb
        ports:
            - 8081:8080
            - 38888:38888
        environment:
            - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
            - RAVEN_Setup_Mode=None
            - RAVEN_License_Eula_Accepted=true
            - "RAVEN_ServerUrl=http://0.0.0.0:8080"
            - "RAVEN_PublicServerUrl=http://ravendb:8080"
            - "RAVEN_ServerUrl_Tcp=tcp://0.0.0.0:38888"
            - "RAVEN_PublicServerUrl_Tcp=tcp://localhost:38888"