version: "3.9"
#ref: https://www.davidboike.dev/2019/06/creating-a-ravendb-cluster-in-docker/
services:
    raven1:
        container_name: raven1
        image: ravendb/ravendb
        ports:
            - 8081:8080
            - 38888:38888
        environment:
            - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
            - RAVEN_Setup_Mode=None
            - RAVEN_License_Eula_Accepted=true
            - "RAVEN_ServerUrl=http://0.0.0.0:8080"
            - "RAVEN_PublicServerUrl=http://localhost:8081"
            - "RAVEN_ServerUrl_Tcp=tcp://0.0.0.0:38888"
            - "RAVEN_PublicServerUrl_Tcp=tcp://localhost:38888"
    raven2:
        container_name: raven2
        image: ravendb/ravendb
        ports:
            - 8082:8080
            - 38889:38888
        environment:
            - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
            - RAVEN_Setup_Mode=None
            - RAVEN_License_Eula_Accepted=true
            - "RAVEN_ServerUrl=http://0.0.0.0:8080"
            - "RAVEN_PublicServerUrl=http://localhost:8082"
            - "RAVEN_ServerUrl_Tcp=tcp://0.0.0.0:38888"
            - "RAVEN_PublicServerUrl_Tcp=tcp://localhost:38889"
    raven3:
        container_name: raven3
        image: ravendb/ravendb
        ports:
            - 8083:8080
            - 38890:38888
        environment:
            - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
            - RAVEN_Setup_Mode=None
            - RAVEN_License_Eula_Accepted=true
            - "RAVEN_ServerUrl=http://0.0.0.0:8080"
            - "RAVEN_PublicServerUrl=http://localhost:8083"
            - "RAVEN_ServerUrl_Tcp=tcp://0.0.0.0:38888"
            - "RAVEN_PublicServerUrl_Tcp=tcp://localhost:38890"